app/models.py
from flask_login import UserMixin
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
from werkzeug.security import generate_password_hash

db = SQLAlchemy()  #this will translate SQL into Python

cart = db.Table('cart',
    db.Column('user_id', db.Integer, db.ForeignKey('user.id')),
    db.Column('product_id', db.Integer, db.ForeignKey('product.id'))
)

#create our Models based off of our ERD
class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), nullable=False, unique = True)
    email = db.Column(db.String(150), nullable=False, unique = True)
    password = db.Column(db.String(250), nullable=False)
    apitoken = db.Column(db.String, default=None, nullable=True)
    cart = db.relationship("Product",
        secondary = cart,
        backref = 'shoppers',
        lazy = 'dynamic'
        )

    def __init__(self, username, email, password):
        self.username = username
        self.email = email
        self.password = generate_password_hash(password)
        self.apitoken

    def add(self, product):
        self.cart.append(product)
        db.session.commit()

    def delete(self, product):
        self.cart.remove(product)
        db.session.commit()
    
    def myCart(self):
        mycart = Product.query.join(cart, (Product.id == cart.c.product_id)).filter(cart.c.user_id == self.id)
        return mycart 

    def deleteall(self):
        db.session.query(cart).delete()
        db.session.commit()

    def to_dict(self):
        return {
            'id': self.id,
            'username': self.username,
            'email': self.email,
            'token': self.apitoken
        }
        
class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    product_name = db.Column(db.String(150), nullable=False)
    img_url = db.Column(db.String(300))
    description = db.Column(db.String(300))
    price = db.Column(db.Numeric(10,2))

    def __init__(self, name,img,desc,price):
        self.product_name = name
        self.img_url = img
        self.description = desc
        self.price = price

    def to_dict(self):
        return {
            'id': self.id,
            'product_name': self.product_name,
            'img_url': self.img_url,
            'description': self.description,
            'price': self.price
        }

app/__init__.py
from flask import Flask
from config import Config
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_moment import Moment
from flask_cors import CORS


#import Blueprints
from .auth.routes import auth
from .shop.routes import shop
from .models import User

app = Flask(__name__)
login = LoginManager()
moment = Moment(app)
CORS(app)


@login.user_loader
def load_user(user_id):
    return User.query.get(user_id)

app.register_blueprint(auth)
app.register_blueprint(shop)
app.config.from_object(Config)

from .models import db


db.init_app(app)
migrate = Migrate(app, db)
login.init_app(app)

login.login_view = 'auth.logMeIn'

from . import routes
from . import models

app/routes.py
from app import app
from flask import render_template

@app.route('/')
def index():
    return render_template('index.html')

app/shop/routes.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from ..apiauthhelper import token_required
from flask_login import current_user, login_required
from app.models import User, Product, db

shop = Blueprint('shop', __name__, template_folder='shoptemplates')

# ============ API ROUTES =====================
@shop.route('/api/products')
def getAllProducts():
    products = Product.query.all()

    return {
        'status': 'ok',
        'products': [p.to_dict() for p in products] 
    }

@shop.route('/api/products/<int:product_id>')
def getOneProduct(product_id):
    product = Product.query.get(product_id)
    return {
        'status': 'ok',
        'product': product.to_dict()
    }

@shop.route('/api/cart')
@token_required
def getCart(user):

    return {
        'status': 'ok',
        'cart': [p.to_dict() for p in user.getCart()]
        }

@shop.route('/api/cart/add', methods=["POST"])
@token_required
def addToCart(user):
    data = request.json
    product_id = data['productId']
    product = Product.query.get(product_id)
    user.addToCart(product)
    return {'status': 'ok','message': 'Succesfully added to cart.'}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="assets/css/style.css">
<link rel="stylesheet" href="{{ url_for('static', filename = 'css/main.css') }}">
<title>Chicago Cameras</title>
</head>
<body>
    {% include 'navbar.html' %}

    {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
        {% for c, m in messages %}
        <div class="alert alert-{{ c }} alert-dismissible fade show" role="alert">
            {{ m }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    {% endif %}
    {% endwith %}
    
    {% block content %}





    {% endblock %}


<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

    {% block content %}
    <img src="https://static.bhphotovideo.com/explora/sites/default/files/styles/960/public/ctv-793-ts.png?itok=orReGgdI" class="img-fluid" alt="...">
    
    {% for p in products %}
    <div class="container">
        <div class="row">
        
        <a class="card text-decoration-none text-dark" style="width: 18rem;" href ="{{ url_for('shop.getOneProduct', product_id=p.id) }}">
            <img src="{{ p.img_url }}" class="card-img-top" alt="{{ p.product_name }}">
            <div class="card-body">
              <h1 class="card-title">{{ p.product_name }}</h1>
              <p class="card-text">{{ p.description }}</p>
              <small>
                {{ p.price }}
              </small>
            </div>
        </a>
    {% endfor %}
        
        </div>
    </div>

    {% endblock %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Chicago Cameras</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/products">Store</a>
          </li>
          {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="/cart">My Cart</a>
            </li>
          {% endif %}

          {% if current_user.is_authenticated %}
          <li class="nav-item"><a class="nav-link" href="/logout">Log Out</a></li>
          {% else %}
          <li class="nav-item"><a class="nav-link" href="/login">Login</a></li>
          <li class="nav-item"><a class="nav-link" href="/signup">Signup</a></li>
          {% endif %}
            </ul>
          </li>
          <li class="nav-item">
            {% if current_user.is_authenticated %}
            <p class="nav-link">Hello {{ current_user.username }}</p>
            {% else %}
            <p class="nav-link">Hello, Guest</p>
            {% endif %}
          </li>
        </ul>
      </div>
    </div>
</nav>